version: '2'
services:
  pokeapialeademo-app:
    image: pokeapialeademo
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pokeapialeademo-postgresql:5432/PokeApiAleaDemo
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  pokeapialeademo-postgresql:
    extends:
      file: postgresql.yml
      service: pokeapialeademo-postgresql
